#!groovy

def app
def pathToCi = 'watermark/ci'
def dockerfile= 'dockerfile'

def getUserUid() {
    return sh(returnStdout: true, script: 'id -u').trim()
}

def build(name, file = 'watermark/ci/ubuntu.dockerfile watermark/ci', customParams = '') {
    return docker.build("$name-test", "--build-arg uid=${getUserUid()} -f $file")
}

node {
    stage ('Checkout'){
        checkout scm
    }
    stage ('Build docker environment'){
        sh "pwd"
        sh "ls ${pathToCi}"
        sh "echo building"
        app = build('watermark')
    
    }
    testNodeWrapper(app)
    stage ('Building'){
        app.inside {
            sh "rustc --version"
            sh "gcc --version"
            sh "cd watermark; cargo build"
        }
    }

    stage ('Testing'){
        sh "echo Testing"
        app.inside {
            sh "cd watermark; cargo test"
        }
    }
}

def testNodeWrapper(env) {
    dir ('watermark/wrappers/node'){
        stage ('Test Node Wrapper'){
            env.inside {
                sh 'npm -v'
                sh 'npm install'
                sh 'npm test'
            }
        }
        stage ('Build Node Package'){
        }
    }
}


