#!groovy

def app
def pathToCi = 'watermark/ci'
def dockerfile= 'dockerfile'

def getUserUid() {
    return sh(returnStdout: true, script: 'id -u').trim()
}

def build(name, file = 'watermark/ci/ubuntu.dockerfile watermark/ci', customParams = '') {
    return docker.build("$name-test", "--build-arg uid=${getUserUid()} -f $file")
}

node {
    stage ('Checkout'){
        checkout scm
    }

    stage ('Build docker environment'){
        sh "pwd"
        sh "ls ${pathToCi}"
        sh "echo building"
        app = build('watermark')
    
    }
    stage ('Test Building Python Wrapper') {
        dir('watermark/wrappers/python'){
            app.inside {
                sh "echo Test: Test python wrapper"
                sh "ls"
                sh "pwd"
                sh '''
                    python3.5 -m pip install --user -e .
                    python3.5 -m pytest
                    python3.5 setup.py sdist
                    echo Testing that package exists:
                    test -f dist/python3-cxs-0.0.1.tar.gz
                '''
            
                
            }
        }
    }

    stage ('Building'){
        app.inside {
            sh "rustc --version"
            sh "gcc --version"
            sh "cd watermark; cargo build"
        }
    }

    stage ('Testing'){
        sh "echo Testing"
        app.inside {
            sh "cd watermark; cargo test"
        }
    }


}


