# Development
FROM ubuntu:16.04

ARG uid=1000


# Update environment
# JRE installation and gcc
RUN apt-get update -y && apt-get install -y \
    curl \
    build-essential \
    libsodium-dev \
    libssl-dev \
    libgmp3-dev \
    libsqlite0 \
	software-properties-common

# Install libindy
RUN mkdir -p /libindy
WORKDIR /libindy

# add sovrin repo
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 68DB5E88
RUN add-apt-repository "deb https://repo.sovrin.org/sdk/deb xenial stable"
RUN add-apt-repository "deb https://repo.sovrin.org/sdk/deb xenial master"

## install certificates for evernym
RUN mkdir -p /usr/local/share/ca-certificates
RUN curl -k https://repo.corp.evernym.com/ca.crt | tee /usr/local/share/ca-certificates/Evernym_Root_CA.crt
RUN update-ca-certificates

# add evernym repo
RUN curl https://repo.corp.evernym.com/repo.corp.evenym.com-sig.key | apt-key add -
RUN echo 'deb https://repo.corp.evernym.com/deb evernym-agency-dev-ubuntu main' | tee /etc/apt/sources.list.d/agency-dev_repo.corp.evernym.com.list

ENV LIBINDY_DEB=libindy_1.3.0_amd64.deb
ENV LIBINDY_DOWNLOAD_URL=https://repo.sovrin.org/sdk/lib/apt/xenial/stable/$LIBINDY_DEB

RUN curl -fsOSL $LIBINDY_DOWNLOAD_URL \
    && dpkg -i $LIBINDY_DEB \
    && apt-get -f install

RUN mkdir -p /libvcx
WORKDIR /libvcx

ENV VER=0.1.3919265-89e0a35
RUN curl -k -O https://repo.corp.evernym.com/deb/pool/main/libv/libvcx/libvcx_${VER}_amd64.deb
RUN dpkg -i libvcx_${VER}_amd64.deb
