# Development
FROM libindy

RUN apt-get update -y && apt-get install -y \
	libffi-dev \
	ruby \
	ruby-dev \
	sudo \
	rubygems

# Install Rust
ENV RUST_ARCHIVE=rust-1.25.0-x86_64-unknown-linux-gnu.tar.gz
ENV RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE

RUN mkdir -p /rust
WORKDIR /rust

RUN curl -fsOSL $RUST_DOWNLOAD_URL \
    && curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum -c - \
    && tar -C /rust -xzf $RUST_ARCHIVE --strip-components=1 \
    && rm $RUST_ARCHIVE \
    && ./install.sh

# fpm for deb packaging of npm
RUN gem install fpm
RUN apt-get install rpm -y

# Install Nodejs 
# does this install python?!?
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \
    && apt-get install -y nodejs

RUN npm install typescript-compiler

ARG uid=1000
RUN useradd -ms /bin/bash -u $uid vcx
USER vcx

# cargo deb for debian packaging of libvcx
RUN cargo install cargo-deb --color=never

