#!groovy

def dockerfile= 'dockerfile'

def TEST_MODE=true
def NODE_CONTEXT='ubuntu'
if (TEST_MODE) {
    NODE_CONTEXT='ubuntu-12'
}
def getUserUid() {
    return sh(returnStdout: true, script: 'id -u').trim()
}

def build(name, file, context='.', customParams = '') {
    return docker.build("$name", "${customParams} --build-arg uid=${getUserUid()} -f $file $context")
}

def getVcxVersion(envn){
    envn.inside {
        sh 'ls -al'
        sh "echo \$PYTHONPATH"
        sh 'whoami'
        sh 'ls /scripts'
        version = sh(
            script: "export PYTHONPATH=\$PYTHONPATH:/scripts; python3 -c 'import toml_utils; print(toml_utils.get_version_from_file(\"vcx/libvcx/Cargo.toml\"))'",
            returnStdout: true
        )
        return version
    }
}

node(NODE_CONTEXT) {
    try {
        stage ('Checkout'){
            checkout scm
        }
        stage ('VCX-PYTHON testing') {
            libvcx = build('libvcx', 'vcx/ci/Dockerfile-libvcx-test1', 'vcx')
            vcx_python = build('python', 'vcx/wrappers/python3/ci/Dockerfile-python-wrapper-test1', 'vcx')
            // create pip installable artifact
            VCX_VERSION = getVcxVersion(vcx_python)
            sh "echo ${VCX_VERSION}"
            createPtyhonArtifact(vcx_python, VCX_VERSION)
        }
                        
    } catch (Exception ex) {
        currentBuild.result = "FAILED"
        if (env.BRANCH_NAME == "master") {
            fail()
        }
        echo "$ex error"
    } finally {
        step([$class: 'WsCleanup'])
    }
}

def buildDocker(){
    def app
    def pathToCi = 'vcx/ci'
    stage ('Build docker environment'){
        sh "pwd"
        sh "ls ${pathToCi}"
        sh "echo building"
        app = build('vcx')
    }
    return app
}

def testPythonWrapper(envn){
    stage ("Testing Python Wrapper"){
        envn.inside {
            sh "python3 -m pytest"
        }
    }
}

def buildRust(envn){
    stage ('Building Rust Library'){
        envn.inside {
            sh "ls -l"
            sh "rustc --version"
            sh "gcc --version"
            sh "cd vcx/libvcx; cargo build --features ci --color=never"
        }
    }
}

def testRust(envn) {
    stage ('Testing Rust'){
        sh "echo Testing"
        envn.inside {
            sh "cd vcx/libvcx; cargo test --color=never -- --test-threads=1"
        }
    }
}

def createPtyhonArtifact(envn, version) {
    stage ('Building Python Artifact') {
        dir('vcx/wrappers/python3'){
            sh 'echo Building Python Artifact'
            envn.inside {
                sh(
                   script: "export VCX_VERSION=${version}; python3 setup.py sdist",
                    returnStdout: true
                )
                archiveArtifacts allowEmptyArchive: true, artifacts: 'dist/**/*.tar.gz'
            }
        }
    }
}

// updates the path to include the scripts, 
// needed for cargo commands
def updatePath(app) {
    dir ('vcx/ci/scripts') {
        app.inside {
            sh 'export PATH=$PATH:`pwd`'
        }
    }
}


// Update the version and revision in the Cargo.toml file, also the so file .
def updateVersions(app) {
        stage('Updating Versions') {
            app.inside {
                sh 'ls -l'
                // TODO fix this ... these *SHOULD* be cargo commands.
                sh 'cd vcx/libvcx; ls -l; ls ../ci/scripts'
                sh 'cd vcx/libvcx; python ../ci/scripts/cargo-update-version'

            }
        }
}

def updateSo(app) {
    stage('Updating .so file version') {
        app.inside {
            sh 'cd vcx/libvcx; python ../ci/scripts/cargo-update-so'
        }
    }
}


// Creates the debian package for the library, as well as gzips the libvcx.so.<version> file
// Publishes both artifacts.
def createDeb(envn) {
    stage('Build libvcx Debian and compress .so file') {
        envn.inside {
            CERT_SCRIPT = 'vcx/ci/scripts/getCert.sh'
            SCRIPT = 'vcx/ci/scripts/gzip_so_file.py'
            FILES = 'vcx/libvcx/target/debug/libvcx.so.* vcx/libvcx/scripts/provision_agent_keys.py'
            DEST = 'libvcx.tar.gz'

            // get Evernym Certificate onto machine
            sh "${CERT_SCRIPT}"
                
            // build debian
            sh 'cd vcx/libvcx/; cargo deb --no-build'
    

            if (env.BRANCH_NAME == "master") {
                // archive debian to Jenkins
                archiveArtifacts allowEmptyARchive: true, artifacts: "vcx/libvcx/target/debian/libvcx_*_amd64.deb"

                // archive .so file to Jenkins
                sh "python ${SCRIPT} ${FILES} ${DEST}"
                archiveArtifacts allowEmptyARchive: true, artifacts: DEST

                // upload debian to Repo
                withCredentials([usernameColonPassword(credentialsId: 'jenkins-kraken-svc', variable: 'KRAKEN_CREDENTIALS')]) {
                    sh "find vcx/libvcx/target/debian/ -type f -name 'libvcx_*_amd64.deb' -exec curl --cacert /tmp/cert/ca.crt -u \"${KRAKEN_CREDENTIALS}\" -X POST https://kraken.corp.evernym.com/repo/agency_dev/upload -F file=@{} \\;"
                }
            }
        }
    }
}


// Creates the tgz file that can be 'npm install'-ed.
def testNodeWrapper(envn) {
    stage ('Test Node Wrapper'){
        dir('vcx/wrappers/node'){
            envn.inside() {
                sh 'npm install'
                sh 'npm -v'
                sh 'npm run lint'
                sh 'npm run compile'
                sh 'npm test'
                sh 'npm pack'
                archiveArtifacts allowEmptyArchive: true, artifacts: '**/*.tgz'
            }
        }
    }
}


// Creates debian that can install through npm.
def createNpmDeb(app){
  dir('vcx') {
    stage ('Create Npm Deb') {
      app.inside {
        // TODO make this a version number from the script somehow.
        sh 'ls'
        sh 'python ci/scripts/create_npm_deb.py wrappers/node/vcx-*.tgz'
        sh 'ls'
        archiveArtifacts allowEmptyArchive: true, artifacts: 'vcx*.deb'
      }
    }
  }
}

def fail() {
    def message = [
        message: "$JOB_NAME - Build # $BUILD_NUMBER - fail: Check console output at $BUILD_URL to view the results."
    ]
    slackSend message
}

