# Development
FROM libvcx
USER root

RUN apt-get update && apt-get install -y python3

RUN apt-get install -y python3-pip

RUN pip3 install pytest qrcode pytest-asyncio

ENV PYTHONPATH=$PYTHONPATH:/sdk/vcx/wrappers/python3

CMD [ "/sdk/vcx/wrappers/python3/ci/test-python.sh" ]

