# Development
FROM libindy

ARG uid=1000

RUN apt-get update && apt-get install -y python3

RUN apt-get install -y python3-pip

RUN pip3 install pytest qrcode pytest-asyncio

ENV PYTHONPATH=$PYTHONPATH:/python3

RUN mkdir -p /scripts
COPY vcx/ci/scripts/ /scripts

WORKDIR /python3/tests

CMD [ "/sdk/vcx/wrappers/python3/ci/test-python.sh" ]

