const { assert } = require('chai')
const cxs = require('../dist')
const { issuerClaimTests } = require('./issuerClaimTests')
const { proofTests } = require('./proof-test')
const { issuerClaimFfiTests } = require('./issuerClaimFfiTests.js')
const { connectionTests } = require('./connectionTests')
const { stubInitCXS } = require('./helpers')

describe('Running tests', async function () {
  this.timeout(10000)
  before(async function () {
    stubInitCXS()
    await cxs.initCxs('ENABLE_TEST_MODE')
  })
  it('initCxs is stubbed', async function () {
    const spyInitCxs = stubInitCXS()
    assert.equal(spyInitCxs.calledOnce, true)
    await cxs.initCxs('ENABLE_TEST_MODE')
    assert.equal(spyInitCxs.calledTwice, true)
  })
  it('Issuer Claim tests', issuerClaimTests)
  it('Proof Tests', proofTests)
  it('Issuer Claim Ffi Tests', issuerClaimFfiTests)
  it('Connection Tests', connectionTests)
})
