source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/evernym/sdk.git'

platform :ios, '10.0'

# workspace 'ConnectMeVCX.xcworkspace'

# def appPods
#      use_frameworks!
# end

# target 'ConnectMeVCX' do
#   project 'ConnectMeVCX/ConnectMeVCX.xcodeproj'
#   appPods
# end

# target 'ConnectMe-demo' do
#    project 'ConnectMe-demo/ConnectMe-demo.xcodeproj'
#    appPods

#  target 'ConnectMe-demoTests' do
# 	inherit! :search_paths
#     end
# end