# Development
FROM nodejs

ARG uid=1000
RUN useradd -ms /bin/bash -u $uid vcxnode

# Assumes we are in the ./vcx directory
COPY libvcx/target/debug/libvcx.so /usr/lib
COPY wrappers/node/ /node
RUN chown -R vcxnode:vcxnode /node
RUN chmod 755 /node
WORKDIR /node
RUN npm install typescript-compiler
RUN npm install
CMD ["/bin/bash", "ci/test_wrapper.sh"]

