# Development
FROM nodejs

ARG uid=1001
RUN useradd -ms /bin/bash -u $uid vcxnode

# Assumes we are in the ./vcx directory
COPY libvcx/target/debug/libvcx.so /usr/lib
COPY wrappers/node/ /node
WORKDIR /node
RUN npm install typescript-compiler
RUN npm install
RUN chown -R vcxnode:vcxnode /node
RUN chmod 755 /node
USER vcxnode


